name: Laravel Testing with MySql DB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: api
          submodules: recursive


      - name: Checkout api repo
        uses: actions/checkout@v3
        with:
          repository: S-DICKSON/Laravel-6-DevSecOps-API
          path: main
          submodules: recursive


      - name: Install Dependencies for main
        run: cd main && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions for main
        run: cd main && chmod -R 777 storage bootstrap/cache

      - name: Clear Config 🗑️
        run: |
          cd main && php artisan config:clear
          php artisan cache:clear

      - name: Prepare the application 🔧
        run: |
          cd main && cp .env.ci .env
          php artisan key:generate

      - name: Migrate and seed database
        run: cd main && php artisan migrate --seed

        #API SETUP

      - name: Install Dependencies for API
        run: cd api && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions for main
        run: cd api && chmod -R 777 storage bootstrap/cache

      - name: Clear Config 🗑️
        run: |
          cd api && php artisan config:clear
          php artisan cache:clear

      - name: Prepare the application 🔧
        run: |
          cd api && cp .env.ci .env
          php artisan key:generate

      - name: Execute tests api repo via PHPUnit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_PORT: 3306

        run: cd api && vendor/bin/phpunit
